server:
  port: 8080


openai:
  api:
    key: Bearer d002b32f190d7b1ae0bc58b148133774.SD8HCsqGHraP8lWr  # 从环境变量获取
    endpoint: http://192.168.3.55/v1/chat/completions  # OpenAI Chat API 端点

logging:
  level:
    root: INFO    # 设置全局日志级别为INFO
    com.ll.stream.controller: DEBUG  # 针对特定包设置日志级别
