server:
  port: 8080


openai:
  api:
    apiKey: Bear sdsdsdsd  # 从环境变量获取
    endPoint: http://localhost:8080/url  # OpenAI Chat API 端点

logging:
  level:
    root: INFO    # 设置全局日志级别为INFO
    com.llm.stream.controller: DEBUG  # 针对特定包设置日志级别
