server:
  port: 8080


openai:
  api:
    key: ********************  # 从环境变量获取
    endpoint: *******************  # OpenAI Chat API 端点

logging:
  level:
    root: INFO    # 设置全局日志级别为INFO
    com.ll.stream.controller: DEBUG  # 针对特定包设置日志级别
