server:
  port: 8081


openai:
  api:
    apiKey: Bearer d002b32f190d7b1ae0bc58b148133774.SD8HCsqGHraP8lWr
    endPoint: http://192.168.3.55/v1/chat/completions


logging:
  level:
    root: INFO    # 设置全局日志级别为INFO
    com.llm.stream.controller: DEBUG  # 针对特定包设置日志级别
